<?php
return [
    'adminEmail' => 'vvdung88@gmail.com',
    'supportEmail' => 'support@example.com',
    'user.passwordResetTokenExpire' => 3600,
    'brandName' => ' ',
    'projectName' => '',
    'device_port' => '8880',
    'unit_amperage' => 'A',
    'unit_voltage' => 'V',
    'unit_temperature' => 'C',
    'unit_humidity' => '%',
    'unit_capacity' => 'Kw',
    'unit_consume' => 'Kwh',
    'unit_frequency' => 'Hz',
    'binary_length' => 10,
    'color_of_good' => '#00BB00',
    'color_of_great' => '#2459D7',
    'color_of_bad' => '#FF0000',
    'color_of_active' => 'black',
    'color_of_inactive' => 'gray',
    'cam_host' => 'ecasmart.homelinux.com',
    'cam_port' => '8888',
    'cam_username' => 'ecaprovn',
    'cam_password' => '1q2w3e4r',
    'page_size' => 20,
    'json_station_file' => 'locations.json',
    'baseUrl' => '/',
    'dir_locations'  => '/locations/',
];
